# Generated by Django 5.2.2 on 2025-08-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='primary_instrument',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('guitalele', 'Guitalele'), ('ukulele', 'Ukulele'), ('baritone_ukulele', 'Baritone Ukulele'), ('banjo', 'Banjo'), ('mandolin', 'Mandolin')], default='ukulele', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='secondary_instrument',
            field=models.CharField(blank=True, choices=[('guitar', 'Guitar'), ('guitalele', 'Guitalele'), ('ukulele', 'Ukulele'), ('baritone_ukulele', 'Baritone Ukulele'), ('banjo', 'Banjo'), ('mandolin', 'Mandolin')], default=None, max_length=20, null=True),
        ),
    ]
