# Generated by Django 5.2.2 on 2025-11-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userpreference_primary_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='known_chords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
