# Generated by Django 5.2.2 on 2025-11-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpreference_known_chords'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='use_known_chord_filter',
            field=models.BooleanField(default=False),
        ),
    ]
