# Generated by Django 5.2.2 on 2026-01-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpreference_use_known_chord_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='secondary_instrument',
            field=models.CharField(blank=True, choices=[('guitar', 'Guitar'), ('guitalele', 'Guitalele'), ('ukulele', 'Ukulele'), ('baritone_ukulele', 'Baritone Ukulele'), ('banjo', 'Banjo'), ('mandolin', 'Mandolin')], max_length=20, null=True),
        ),
    ]
