# Generated by Django 5.2.2 on 2026-03-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='chord_bracket_style',
            field=models.CharField(choices=[('square', 'Square brackets [Am]'), ('parentheses', 'Parentheses (Am)'), ('curly', 'Curly braces {Am}')], default='square', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='chord_color',
            field=models.CharField(choices=[('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], default='black', max_length=10),
        ),
    ]
