# Generated by Django 5.2.2 on 2026-05-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userpreference_chord_bracket_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='chord_color',
            field=models.CharField(choices=[('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], default='red', max_length=10),
        ),
    ]
