# Generated by Django 5.1.2 on 2025-02-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userpreference_is_printing_alternate_chord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='chord_color',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='chord_diagram_position',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='chord_placement',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='chord_weight',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='line_spacing',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='text_color',
        ),
    ]
