# Generated by Django 5.2.2 on 2026-09-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userpreference_chord_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='auto_scroll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='font_size',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='font_style',
            field=models.CharField(choices=[('sans-serif', 'Sans-serif'), ('serif', 'Serif'), ('monospace', 'Monospace')], default='sans-serif', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='line_spacing',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('relaxed', 'Relaxed')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='scroll_speed',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='teleprompter_style',
            field=models.CharField(choices=[('inline', 'Chord symbols inline'), ('beginner', 'Chord diagrams above lyrics')], default='inline', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
