# Generated by Django 5.2.2 on 2025-11-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube_prep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaic',
            name='cubes',
            field=models.ManyToManyField(blank=True, related_name='mosaics', to='cube_prep.cube'),
        ),
    ]
