# Generated by Django 5.2.2 on 2025-11-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube_prep', '0002_mosaic_cubes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cube',
            name='moves',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
