# Generated by Django 5.2.2 on 2026-02-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube_prep', '0003_cube_moves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cube',
            name='moves',
        ),
        migrations.RemoveField(
            model_name='mosaic',
            name='cubes',
        ),
        migrations.AlterField(
            model_name='cube',
            name='colors',
            field=models.JSONField(help_text='3x3 face colors'),
        ),
    ]
