# Generated by Django 5.2.2 on 2026-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube_prep', '0004_remove_cube_moves_remove_mosaic_cubes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaic',
            name='is_collaborative',
            field=models.BooleanField(default=False),
        ),
    ]
