# Generated by Django 5.1.2 on 2024-11-15 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tuning', models.JSONField(help_text="List of strings tuning, e.g., ['G', 'C', 'E', 'A']")),
                ('is_lefty', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frets', models.JSONField(help_text='List of fret positions for each string, e.g., [0, 0, 0, 3]')),
                ('fingers', models.JSONField(blank=True, help_text='List of finger positions, e.g., [0, 0, 0, 3]', null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chords', to='monAccordeur.instrument')),
            ],
        ),
    ]
