# Generated by Django 5.1.2 on 2024-11-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monAccordeur', '0002_remove_instrument_is_lefty'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='is_lefty',
            field=models.BooleanField(default=False),
        ),
    ]
