# Generated by Django 5.1.2 on 2024-11-16 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monAccordeur', '0003_instrument_is_lefty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='is_lefty',
        ),
    ]
