# Generated by Django 5.1.2 on 2024-11-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monAccordeur', '0004_remove_instrument_is_lefty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chord',
            name='fingers',
            field=models.JSONField(blank=True, help_text='List of finger positions, e.g., [1, 2, 3, 4]', null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
