# Generated by Django 5.2.2 on 2026-09-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
    ]
