# Generated by Django 5.2.2 on 2026-10-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_group_contact_phone_group_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='landing_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_landing/'),
        ),
    ]
