# Generated by Django 5.2.2 on 2026-10-09 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_group_landing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='landing_image',
            field=models.ImageField(blank=True, help_text='Square image (e.g. 600×600 px) shown on the landing page card.', null=True, upload_to='group_landing/'),
        ),
        migrations.CreateModel(
            name='GroupContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, help_text='e.g. Leader, Treasurer, Membership', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers are shown first.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.group')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
