"""
Django settings for FrancoUke project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-31v71%x^441-$wdk*9vmkqq^5xnfk!e0%6+_-_^6paegiqe$_1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

X_FRAME_OPTIONS = 'SAMEORIGIN'  # Allows embedding on the same domain


# Application definition

INSTALLED_APPS = [
    'nested_admin',
    'tinymce',
    'songbook.apps.SongbookConfig',
    'users.apps.UsersConfig',
    'crispy_forms',
    'crispy_bootstrap4',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'taggit',
    'core',
    'board',
    'django.contrib.sites',
    "rest_framework",
    'public',
    'assets',
    'teleprompter',
     "setlists",   # 👈 make sure this is here


    

]

SITE_ID = 1

MIDDLEWARE = [
    'core.middleware.path_based_site.PathBasedSiteMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FrancoUke.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # <── add this
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'songbook.context_processors.site_context',

            ],
        },
    },
]

SILENCED_SYSTEM_CHECKS = [
    'ckeditor.W001',
]

TINYMCE_DEFAULT_CONFIG = {
    "height": 250,  # Comfortable default height
    "width": "100%",  # Expand to container width
    "menubar": False,  # Hide top menus (File/Edit/View etc.)
    "statusbar": True,  # Keep bottom resize/status bar
    "resize": True,  # Allow user to resize editor

    # ✨ Light, focused toolbar
    "toolbar": (
        "undo redo | bold italic underline | bullist numlist | "
        "link unlink | blockquote | removeformat | code"
    ),

    # 🎛️ Useful plugins, nothing bloated
    "plugins": "link lists code paste",
    "branding": False,  # Removes “Powered by TinyMCE”
    "cleanup_on_startup": True,
    "custom_undo_redo_levels": 10,
    "paste_as_text": True,  # Prevent weird formatting from Word/Google Docs
}





WSGI_APPLICATION = 'FrancoUke.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

import os

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

AUTH_USER_MODEL = 'users.CustomUser'



STATIC_URL = '/static/'

# URL to use when referring to static files
STATIC_URL = '/static/'

# Directory where Django will collect static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Use during deployment

# Additional directories to search for static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),                # your app-wide static assets
    os.path.join(BASE_DIR, 'songbook', 'chords'),    # 🎸 make chord JSONs accessible
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CCRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

CRISPY_TEMPLATE_PACK = 'bootstrap4'

#Pour desactive la version strumsphere
ENABLE_STRUMSPHERE = True

#LOGIN_REDIRECT_URL = 'songbook-home'

LOGIN_URL = '/users/login/'  # ✅ Fix the redirect issue
LOGIN_REDIRECT_URL = '/'  # ✅ Ensure users go to home after login
LOGOUT_REDIRECT_URL = '/'  # ✅ Ensure users go home after logout

TAGGIT_CASE_INSENSITIVE = True

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
