"""
Django settings for FrancoUke project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-31v71%x^441-$wdk*9vmkqq^5xnfk!e0%6+_-_^6paegiqe$_1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

X_FRAME_OPTIONS = 'SAMEORIGIN'  # Allows embedding on the same domain


# Application definition

INSTALLED_APPS = [
    'nested_admin',
    'tinymce',
    'songbook.apps.SongbookConfig',
    'users.apps.UsersConfig',
    'crispy_forms',
    'crispy_bootstrap4',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'taggit',
    'core',
    'board',
    'django.contrib.sites',
    "rest_framework",
    'public',
    'assets',
    'francontcube',
    'cube',
    'cube_prep',
    'teleprompter',
    'setlists',
]

SITE_ID = 1

MIDDLEWARE = [
    'core.middleware.path_based_site.PathBasedSiteMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FrancoUke.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'songbook.context_processors.site_context',
            ],
        },
    },
]

SILENCED_SYSTEM_CHECKS = [
    'ckeditor.W001',
]

TINYMCE_DEFAULT_CONFIG = {
    "height": 300,
    "width": "100%",
    "menubar": False,
    "plugins": "advlist autolink lists link charmap preview anchor "
               "searchreplace visualblocks code fullscreen "
               "insertdatetime table paste code help wordcount",
    "toolbar": (
        "undo redo | styles | bold italic underline | "
        "alignleft aligncenter alignright alignjustify | "
        "bullist numlist outdent indent | link | removeformat | help"
    ),
    "block_formats": "Paragraph=p; Heading 1=h1; Heading 2=h2; Heading 3=h3",
    "style_formats": [
        {"title": "Paragraph", "block": "p"},
        {"title": "Heading 1", "block": "h1"},
        {"title": "Heading 2", "block": "h2"},
        {"title": "Heading 3", "block": "h3"},
    ],
    "content_style": "body { font-family: Helvetica, Arial, sans-serif; font-size: 14px }",
}


WSGI_APPLICATION = 'FrancoUke.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ============================================================================
# AUTHENTICATION SETTINGS
# ============================================================================

AUTH_USER_MODEL = 'users.CustomUser'

# Login/Logout URLs and Redirects
LOGIN_URL = 'users:login'       # Where to redirect if login required
LOGIN_REDIRECT_URL = 'landing'  # After successful login → Landing page
LOGOUT_REDIRECT_URL = 'landing' # After logout → Landing page

# Why 'landing'?
# - Users may have multiple roles (song contributor + performer + speedcuber)
# - Landing page lets them choose which app to use
# - Django's ?next= parameter will override this for protected pages
# - Example: Try to access /board/ → Login → Auto-redirect back to /board/

# Note: Most of your apps are PUBLIC with selective authentication:
# - FrancoUke/StrumSphere: Public viewing, auth for editing ChordPro
# - Uke4ia Public: No auth required
# - Uke4ia Performers: Auth required for board/availability/setlists
# - FrancontCube: Public now, will need auth for training timer/leaderboard


# ============================================================================
# STATIC FILES (CSS, JavaScript, Images)
# ============================================================================

STATIC_URL = '/static/'

# Directory where Django will collect static files (for production)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional directories to search for static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),                # App-wide static assets
    os.path.join(BASE_DIR, 'songbook', 'chords'),    # 🎸 Chord JSONs
]


# ============================================================================
# MEDIA FILES (User-uploaded content)
# ============================================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ============================================================================
# CRISPY FORMS SETTINGS
# ============================================================================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = 'bootstrap4'


# ============================================================================
# TAGGIT SETTINGS
# ============================================================================

TAGGIT_CASE_INSENSITIVE = True


# ============================================================================
# FEATURE FLAGS
# ============================================================================

# Pour désactiver la version StrumSphere si nécessaire
ENABLE_STRUMSPHERE = True


# ============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# ============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'