# Generated by Django 5.2.1 on 2025-06-05 09:43

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('songChordPro', models.TextField()),
                ('lyrics_with_chords', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('acknowledgement', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.CharField(choices=[('FrancoUke', 'FrancoUke'), ('StrumSphere', 'StrumSphere')], default='FrancoUke', max_length=20)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='SongFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.JSONField(blank=True, default=dict)),
                ('verse', models.JSONField(blank=True, default=dict)),
                ('chorus', models.JSONField(blank=True, default=dict)),
                ('bridge', models.JSONField(blank=True, default=dict)),
                ('interlude', models.JSONField(blank=True, default=dict)),
                ('outro', models.JSONField(blank=True, default=dict)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songbook.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='songformatting',
            unique_together={('user', 'song')},
        ),
    ]