# Generated by Django 5.2.1 on 2025-06-05 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('songChordPro', models.TextField()),
                ('lyrics_with_chords', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('acknowledgement', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.CharField(choices=[('FrancoUke', 'FrancoUke'), ('StrumSphere', 'StrumSphere')], default='FrancoUke', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SongFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.JSONField(blank=True, default=dict)),
                ('verse', models.JSONField(blank=True, default=dict)),
                ('chorus', models.JSONField(blank=True, default=dict)),
                ('bridge', models.JSONField(blank=True, default=dict)),
                ('interlude', models.JSONField(blank=True, default=dict)),
                ('outro', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
