# Generated by Django 5.2.2 on 2025-08-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='site_name',
            field=models.CharField(blank=True, choices=[('FrancoUke', 'FrancoUke'), ('StrumSphere', 'StrumSphere')], default=None, help_text='Leave empty to hide this song from all platforms', max_length=20, null=True),
        ),
    ]
