# Generated by Django 5.2.2 on 2025-09-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0003_alter_song_site_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['setlist_order', 'songTitle']},
        ),
        migrations.AddField(
            model_name='song',
            name='scroll_speed',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='song',
            name='setlist_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
