# Generated by Django 5.2.2 on 2025-09-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0004_alter_song_options_song_scroll_speed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
        migrations.RemoveField(
            model_name='song',
            name='setlist_order',
        ),
    ]
