# Generated by Django 5.2.2 on 2025-10-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0005_alter_song_options_remove_song_setlist_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='scroll_speed',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Teleprompter scroll speed in pixels per second (default 30 if unset)', null=True),
        ),
    ]
