# Generated by Django 5.2.2 on 2025-10-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0006_alter_song_scroll_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='scroll_speed',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Teleprompter scroll speed in pixels per second (default 30 if unset)', null=True),
        ),
    ]
