# Generated by Django 5.2.2 on 2025-10-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0007_alter_song_scroll_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='revised_on',
            field=models.DateField(blank=True, help_text='Revision date as provided by the contributor (optional)', null=True),
        ),
    ]
