# Generated by Django 5.2.2 on 2025-10-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0008_song_revised_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='songformatting',
            name='centered',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
