# Generated by Django 5.2.2 on 2025-11-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0009_songformatting_centered'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='supplementary_chords',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
