# Generated by Django 5.2.2 on 2025-11-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0010_song_supplementary_chords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='supplementary_chords',
        ),
    ]
