# Generated by Django 5.2.2 on 2026-06-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0011_song_cloned_from_song_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='chords_used',
            field=models.JSONField(blank=True, default=list, help_text='List of unique chords used in this song'),
        ),
    ]
