# Generated by Django 5.2.2 on 2026-01-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0011_remove_song_supplementary_chords'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cloned_from',
            field=models.ForeignKey(blank=True, help_text='Original song if this is a personalized copy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='songbook.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If True, visible to all users. If False, only visible to contributor.'),
        ),
    ]
