# Generated by Django 5.2.2 on 2026-06-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0012_song_chords_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='chords_used',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of unique chords used in this song'),
        ),
    ]
