# Generated by Django 5.1.2 on 2025-01-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0013_song_abc_notation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='abc_notation',
        ),
    ]
