# Generated by Django 5.2.2 on 2026-08-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0013_alter_song_chords_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='default_strumming_pattern',
            field=models.CharField(blank=True, default='', help_text="e.g. D-DU-UDU. Letters: D (down), U (up), X (mute/chuck), '.' (rest), '-' (separator between beat-groups). Leave blank if the song doesn't use a fixed strum (e.g. fingerpicked).", max_length=30),
        ),
    ]
