# Generated by Django 5.2.2 on 2026-08-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0014_song_default_strumming_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='detected_key',
            field=models.CharField(blank=True, help_text="Automatically detected from the song's chords on save. Not user-entered.", max_length=5, null=True),
        ),
    ]
