# Generated by Django 5.1.2 on 2025-02-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0015_songformatting'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='acknowledgement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
