# Generated by Django 5.2.2 on 2026-09-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0015_song_detected_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='origin',
            field=models.CharField(blank=True, default='', help_text='Short code for where this version came from, e.g. NBU, SOUP, I-UKE, OZBCOZ (free text).', max_length=20),
        ),
    ]
