# Generated by Django 5.2.2 on 2026-09-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0016_song_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='site_name',
            field=models.CharField(blank=True, choices=[('FrancoUke', 'FrancoUke'), ('StrumSphere', 'StrumSphere')], db_index=True, default=None, help_text='Leave empty to hide this song from all platforms', max_length=20, null=True),
        ),
    ]
