# Generated by Django 5.2.2 on 2025-09-11 02:13

import assets.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('other', 'Other')], default='image', max_length=10)),
                ('provider', models.CharField(choices=[('local', 'Local'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('other', 'Other')], default='local', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=assets.models.asset_upload_to)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='assets/thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='assets.tag')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetcollection')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('collection', 'asset')},
            },
        ),
        migrations.AddField(
            model_name='assetcollection',
            name='assets',
            field=models.ManyToManyField(related_name='collections', through='assets.AssetCollectionItem', to='assets.asset'),
        ),
        migrations.CreateModel(
            name='EventAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('per_event_meta', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_usages', to='assets.asset')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['sha256'], name='assets_asse_sha256_1a6fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['uploaded_at'], name='assets_asse_uploade_856564_idx'),
        ),
    ]
