# Generated by Django 5.2.2 on 2026-09-23 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_created_at'),
        ('core', '0002_seed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.group'),
        ),
    ]
