# Generated by Django 5.2.2 on 2026-01-02 02:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuber',
            fields=[
                ('cuber_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
                ('adjective', models.CharField(max_length=50)),
                ('superhero', models.CharField(max_length=50)),
                ('color_code_hash', models.CharField(max_length=128)),
                ('avatar_variant', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_active_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cubeur',
                'verbose_name_plural': 'Cubeurs',
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
