# Generated by Django 5.2.2 on 2026-01-02 11:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubing_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuber',
            options={},
        ),
        migrations.AddField(
            model_name='cuber',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuber_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leader',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leader',
            name='role',
            field=models.CharField(choices=[('teacher', 'Enseignant'), ('coach', 'Entraîneur'), ('club_leader', 'Animateur de Club'), ('parent', 'Parent Responsable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=200)),
                ('group_code', models.CharField(max_length=6, unique=True)),
                ('group_type', models.CharField(choices=[('class', 'Classe'), ('club', 'Club'), ('team', 'Équipe'), ('practice', 'Groupe de Pratique')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('leaders', models.ManyToManyField(related_name='groups', to='cubing_users.leader')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=20)),
                ('cuber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubing_users.cuber')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubing_users.group')),
            ],
            options={
                'unique_together': {('cuber', 'group')},
            },
        ),
    ]
