# Generated by Django 5.2.8 on 2025-12-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CubeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('json_state', models.JSONField()),
                ('algorithm', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('method', models.CharField(choices=[('cubienewbie', 'CubiNewbie'), ('beginner', 'Beginner'), ('cfop', 'CFOP'), ('roux', 'Roux'), ('zz', 'ZZ')], default='beginner', max_length=20)),
            ],
        ),
    ]
