# Generated by Django 5.2.8 on 2025-12-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubestate',
            name='json_highlight',
            field=models.JSONField(blank=True, help_text='Instructional highlighting per sticker', null=True),
        ),
        migrations.AlterField(
            model_name='cubestate',
            name='method',
            field=models.CharField(choices=[('cubienewbie', 'CubieNewbie'), ('beginner', 'Beginner'), ('cfop', 'CFOP'), ('roux', 'Roux'), ('zz', 'ZZ')], default='beginner', max_length=20),
        ),
    ]
