# Generated by Django 5.2.2 on 2025-12-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0002_cubestate_json_highlight_alter_cubestate_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubestate',
            name='roofpig_colored',
            field=models.TextField(blank=True, help_text="Roofpig colored pieces (ex: 'U- D- L* Ufr Ufl')"),
        ),
        migrations.AddField(
            model_name='cubestate',
            name='roofpig_flags',
            field=models.CharField(blank=True, default='showalg', help_text="Roofpig flags (ex: 'showalg speed:2')", max_length=200),
        ),
        migrations.AddField(
            model_name='cubestate',
            name='roofpig_setup',
            field=models.TextField(blank=True, help_text="Roofpig setup moves to position the cube (ex: 'R U R' F' U' F')"),
        ),
    ]
