# Generated by Django 5.2.2 on 2025-12-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0003_cubestate_roofpig_colored_cubestate_roofpig_flags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubestate',
            name='roofpig_colored',
            field=models.TextField(blank=True, help_text="Roofpig colored pieces to highlight (ex: 'U- D- L* Ufr Ufl')"),
        ),
        migrations.AlterField(
            model_name='cubestate',
            name='roofpig_flags',
            field=models.CharField(blank=True, default='showalg', help_text="Roofpig display flags (ex: 'showalg speed:2')", max_length=200),
        ),
    ]
