# Generated by Django 5.2.2 on 2026-02-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0005_add_category_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubestate',
            name='hand_orientation',
            field=models.CharField(choices=[('right', 'Main Droite'), ('left', 'Main Gauche')], default='right', help_text="Quelle main fait les mouvements (détermine l'orientation du cube)", max_length=10),
        ),
    ]
