# Generated by Django 5.2.2 on 2026-03-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0006_cubestate_hand_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubestate',
            name='camera_latitude',
            field=models.FloatField(default=22.0, help_text='cubing.js camera vertical angle. Higher = more top-down view.'),
        ),
        migrations.AddField(
            model_name='cubestate',
            name='camera_longitude',
            field=models.FloatField(default=-25.0, help_text='cubing.js camera horizontal angle. Negative = more front face visible.'),
        ),
        migrations.AddField(
            model_name='cubestate',
            name='stickering',
            field=models.CharField(blank=True, default='full', help_text='cubing.js stickering: full | OLL | PLL | F2L | LL | Cross', max_length=30),
        ),
        migrations.AlterField(
            model_name='cubestate',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cubestate',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cubestate',
            name='hand_orientation',
            field=models.CharField(choices=[('right', 'Main Droite'), ('left', 'Main Gauche')], default='right', max_length=10),
        ),
        migrations.AlterField(
            model_name='cubestate',
            name='json_highlight',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cubestate',
            name='roofpig_colored',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cubestate',
            name='roofpig_flags',
            field=models.CharField(blank=True, default='showalg', max_length=200),
        ),
        migrations.AlterField(
            model_name='cubestate',
            name='roofpig_setup',
            field=models.TextField(blank=True),
        ),
    ]
