# Generated by Django 5.2.2 on 2025-08-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_venue_remove_gig_max_players_gig_arrive_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='location',
        ),
    ]
