# Generated by Django 5.2.2 on 2025-08-04 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_remove_gig_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='created_at',
        ),
        migrations.AddField(
            model_name='gig',
            name='date',
            field=models.DateField(default=datetime.date(2025, 8, 4)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gig',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
