# Generated by Django 5.2.2 on 2025-08-06 23:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_remove_gig_created_at_gig_date_alter_gig_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
