# Generated by Django 5.2.2 on 2025-09-26 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0019_remove_boardmessage_equipment_status_and_more'),
        ('songbook', '0005_alter_song_options_remove_song_setlist_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='Optional: link this setlist to a Uke4ia event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.event')),
            ],
        ),
        migrations.CreateModel(
            name='SetListSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('rehearsal_notes', models.TextField(blank=True)),
                ('scroll_speed', models.PositiveIntegerField(default=40)),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='setlists.setlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songbook.song')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
