# Generated by Django 5.2.2 on 2025-10-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setlistsong',
            options={},
        ),
        migrations.AlterField(
            model_name='setlistsong',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='setlistsong',
            unique_together={('setlist', 'order')},
        ),
    ]
