# Generated by Django 5.2.2 on 2025-10-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0002_alter_setlistsong_options_alter_setlistsong_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setlistsong',
            options={'ordering': ['order']},
        ),
    ]
