# Generated by Django 5.2.2 on 2025-10-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0003_alter_setlistsong_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setlistsong',
            name='scroll_speed',
        ),
    ]
