# Generated by Django 5.2.2 on 2025-10-16 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_alter_rehearsaldetails_options'),
        ('setlists', '0004_remove_setlistsong_scroll_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='event',
            field=models.OneToOneField(blank=True, help_text='Optional: link this setlist to a Uke4ia event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setlist', to='board.event'),
        ),
    ]
