# Generated by Django 5.2.2 on 2025-11-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0005_alter_setlist_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setlistsong',
            name='rehearsal_notes',
        ),
    ]
