# Generated by Django 5.2.2 on 2026-09-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_groups'),
        ('setlists', '0006_remove_setlistsong_rehearsal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to='core.group'),
        ),
    ]
