# Generated by Django 5.2.2 on 2026-09-30 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0030_boardcolumn_group_event_group_venue_group'),
        ('setlists', '0007_setlist_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='event',
            field=models.OneToOneField(blank=True, help_text='Optional: link this setlist to an event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setlist', to='board.event'),
        ),
    ]
