# Generated by Django 5.2.2 on 2025-08-07 10:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarditem',
            name='is_rehearsal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boarditem',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='boarditem',
            name='rich_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
