# Generated by Django 5.2.2 on 2025-08-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_create_performanceavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='boarditem',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='performance',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='board.venue'),
        ),
    ]
