# Generated by Django 5.2.2 on 2025-08-07 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_boarditem_is_rehearsal_boarditem_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RehearsalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yes', "✅ I'm coming"), ('maybe', '❓ Not sure'), ('no', "❌ Can't make it")], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='board.boarditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'rehearsal')},
            },
        ),
    ]
