# Generated by Django 5.2.2 on 2025-08-07 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rehearsalavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='board_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('board_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='board.boarditem')),
            ],
        ),
    ]
