# Generated by Django 5.2.2 on 2025-08-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_venue_alter_boarditem_options_performance_venue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='venue',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
