# Generated by Django 5.2.2 on 2025-08-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_boarditemphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcolumn',
            name='column_type',
            field=models.CharField(choices=[('general', 'General'), ('photos', 'Photo Gallery'), ('venue', 'Venue'), ('songs to listen', 'Songs To Listen'), ('rehearsal', 'Rehearsal'), ('rehearsal notes', 'Rehearsal Notes')], default='general', max_length=20),
        ),
    ]
