# Generated by Django 5.2.2 on 2025-08-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_boardcolumn_column_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarditemphoto',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
