# Generated by Django 5.2.2 on 2025-08-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_event_rich_description_event_rich_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
