# Generated by Django 5.2.2 on 2025-08-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_boarditemphoto_is_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarditem',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boarditem',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardcolumn',
            name='column_type',
            field=models.CharField(choices=[('general', 'General'), ('photos', 'Photo Gallery'), ('venue', 'Venue'), ('songs to listen', 'Songs To Listen'), ('rehearsal', 'Rehearsal'), ('rehearsal notes', 'Rehearsal Notes'), ('past_performances', 'Past Performances')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='boarditem',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
