# Generated by Django 5.2.2 on 2025-08-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_boarditem_end_time_boarditem_start_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardcolumn',
            options={'ordering': ['position']},
        ),
    ]
