# Generated by Django 5.2.2 on 2025-08-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_boardcolumn_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarditem',
            name='arrive_by',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boarditem',
            name='attire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boarditem',
            name='chairs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boarditem',
            name='performance_type',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('tbc', 'To Be Confirmed'), ('past', 'Past Performance')], default='upcoming', max_length=20),
        ),
    ]
