# Generated by Django 5.2.2 on 2025-08-31 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarditem',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='board.boardcolumn'),
        ),
    ]
