# Generated by Django 5.2.2 on 2025-08-19 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_boarditem_arrive_by_boarditem_attire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarditem',
            name='arrive_by',
        ),
        migrations.RemoveField(
            model_name='boarditem',
            name='attire',
        ),
        migrations.RemoveField(
            model_name='boarditem',
            name='chairs',
        ),
        migrations.RemoveField(
            model_name='boarditem',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='boarditem',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='boarditem',
            name='is_rehearsal',
        ),
        migrations.RemoveField(
            model_name='boarditem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='boarditem',
            name='performance_type',
        ),
        migrations.RemoveField(
            model_name='boarditem',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='boardcolumn',
            name='column_type',
            field=models.CharField(choices=[('general', 'General'), ('photos', 'Photo Gallery'), ('venue', 'Venue'), ('songs_to_listen', 'Songs To Listen'), ('rehearsal', 'Rehearsal'), ('rehearsal_notes', 'Rehearsal Notes')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('arrive_by', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('attire', models.CharField(blank=True, max_length=255, null=True)),
                ('chairs', models.CharField(blank=True, max_length=255, null=True)),
                ('performance_type', models.CharField(choices=[('upcoming', 'Upcoming'), ('tbc', 'To Be Confirmed'), ('past', 'Past Performance')], default='upcoming', max_length=20)),
                ('is_rehearsal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='board.boarditem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rehearsalavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rehearsalavailability',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='board.performance'),
        ),
        migrations.AlterUniqueTogether(
            name='rehearsalavailability',
            unique_together={('user', 'performance')},
        ),
        migrations.RemoveField(
            model_name='rehearsalavailability',
            name='rehearsal',
        ),
    ]
