# Generated by Django 5.2.2 on 2025-09-03 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_boarditem_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarditem',
            name='description',
        ),
        migrations.AddField(
            model_name='boarditem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_items', to='board.event'),
        ),
        migrations.AlterField(
            model_name='boarditem',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
