# Generated by Django 5.2.2 on 2025-09-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_remove_boarditem_description_boarditem_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='board_item',
        ),
    ]
