# Generated by Django 5.2.2 on 2025-08-19 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_remove_boarditem_arrive_by_remove_boarditem_attire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('rehearsal', 'Rehearsal'), ('performance', 'Performance'), ('general', 'General Event')], default='performance', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('tbc', 'To Be Confirmed'), ('past', 'Past')], default='upcoming', max_length=20)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='board.boarditem')),
            ],
            options={
                'ordering': ['event_date', 'start_time', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_photos/')),
                ('is_cover', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='board.event')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attire', models.CharField(blank=True, max_length=255, null=True)),
                ('chairs', models.CharField(blank=True, max_length=255, null=True)),
                ('arrive_by', models.TimeField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_details', to='board.event')),
            ],
        ),
        migrations.CreateModel(
            name='RehearsalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_details', to='board.event')),
            ],
        ),
    ]
