# Generated by Django 5.2.2 on 2025-09-04 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_remove_event_board_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='board.boardcolumn'),
        ),
    ]
