# Generated by Django 5.2.2 on 2025-09-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_event_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='arrive_by',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='attire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='chairs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
