# Generated by Django 5.2.2 on 2025-09-04 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_event_arrive_by_event_attire_event_chairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcolumn',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_column', to='board.venue'),
        ),
    ]
