# Generated by Django 5.2.2 on 2025-09-11 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('board', '0015_remove_performanceavailability_performance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_asset',
            field=models.ForeignKey(blank=True, help_text='Optional: choose a shared cover image from the repository', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_events', to='assets.asset'),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('arrive_by', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('attire', models.CharField(blank=True, max_length=255, null=True)),
                ('chairs', models.CharField(blank=True, max_length=255, null=True)),
                ('performance_type', models.CharField(choices=[('upcoming', 'Upcoming'), ('tbc', 'To Be Confirmed'), ('past', 'Past Performance')], default='upcoming', max_length=20)),
                ('is_rehearsal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='board.boarditem')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='board.venue')),
            ],
        ),
    ]
