# Generated by Django 5.2.2 on 2025-09-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('board', '0016_event_cover_asset_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery_assets',
            field=models.ManyToManyField(blank=True, related_name='gallery_for_events', to='assets.asset'),
        ),
    ]
