# Generated by Django 5.2.2 on 2025-09-15 13:26

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_event_gallery_assets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_equipment', models.BooleanField(default=False)),
                ('equipment_status', models.CharField(blank=True, choices=[('ok', 'OK'), ('needs_repair', 'Needs Repair'), ('missing', 'Missing')], max_length=50, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_messages', to=settings.AUTH_USER_MODEL)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='board.boardcolumn')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
