# Generated by Django 5.2.2 on 2025-09-15 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_boardmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmessage',
            name='equipment_status',
        ),
        migrations.RemoveField(
            model_name='boardmessage',
            name='is_equipment',
        ),
        migrations.AddField(
            model_name='boardmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='boardmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardmessage',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=255),
            preserve_default=False,
        ),
    ]
