# Generated by Django 5.2.2 on 2025-10-13 10:09


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_remove_boardmessage_equipment_status_and_more'),
        ('songbook', '0006_alter_song_scroll_speed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehearsaldetails',
            options={'verbose_name': 'Rehearsal Details', 'verbose_name_plural': 'Rehearsal Details'},
        ),
        migrations.AlterField(
            model_name='rehearsaldetails',
            name='notes',
            field=models.TextField(blank=True, help_text='General rehearsal notes', null=True),
        ),
        migrations.AlterModelTable(
            name='rehearsaldetails',
            table='board_rehearsaldetails',
        ),
        migrations.CreateModel(
            name='RehearsalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('body', models.TextField(blank=True, help_text='Rich text notes for this section.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='board.rehearsaldetails')),
            ],
            options={
                'verbose_name': 'Rehearsal Section',
                'verbose_name_plural': 'Rehearsal Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SongRehearsalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(help_text='Rich text rehearsal notes for this song.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_notes', to='board.rehearsalsection')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_notes', to='songbook.song')),
            ],
            options={
                'verbose_name': 'Song Rehearsal Note',
                'verbose_name_plural': 'Song Rehearsal Notes',
                'ordering': ['song', 'created_at'],
            },
        ),
    ]
