# Generated by Django 5.2.2 on 2025-10-13 18:42

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_alter_rehearsaldetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehearsaldetails',
            options={},
        ),
        migrations.AddField(
            model_name='rehearsaldetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rehearsaldetails',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='rehearsaldetails',
            table=None,
        ),
    ]
