# Generated by Django 5.2.2 on 2025-10-14 09:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_alter_rehearsaldetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarditem',
            name='rich_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardmessage',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rich_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rich_notes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rehearsaldetails',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rehearsalsection',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songrehearsalnote',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
