# Generated by Django 5.2.2 on 2025-10-15 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_alter_boarditem_rich_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehearsaldetails',
            options={'verbose_name': 'Rehearsal Detail', 'verbose_name_plural': 'Rehearsal Details'},
        ),
    ]
