# Generated by Django 5.2.2 on 2025-10-18 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_alter_rehearsaldetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrehearsalnote',
            name='rehearsal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.rehearsaldetails'),
        ),
        migrations.AddField(
            model_name='songrehearsalnote',
            name='section_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='songrehearsalnote',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_notes', to='board.rehearsalsection'),
        ),
    ]
