# Generated by Django 5.2.2 on 2025-10-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_songrehearsalnote_rehearsal_and_more'),
    ]

    operations = [
    ]
from django.db import migrations

def move_section_data(apps, schema_editor):
    SongRehearsalNote = apps.get_model('board', 'SongRehearsalNote')
    RehearsalSection = apps.get_model('board', 'RehearsalSection')

    for note in SongRehearsalNote.objects.all():
        if note.section_id:
            try:
                section = RehearsalSection.objects.get(pk=note.section_id)
                note.rehearsal_id = section.rehearsal_id
                note.section_title = section.title
                note.save(update_fields=['rehearsal', 'section_title'])
            except RehearsalSection.DoesNotExist:
                continue

class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_songrehearsalnote_rehearsal_and_more'),  # Replace with your latest migration
    ]

    operations = [
        migrations.RunPython(move_section_data, reverse_code=migrations.RunPython.noop),
    ]
