# Generated by Django 5.2.2 on 2025-10-19 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_migrate_rehearsal_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songrehearsalnote',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='songrehearsalnote',
            options={'ordering': ['song__songTitle', 'created_at'], 'verbose_name': 'Song Rehearsal Note', 'verbose_name_plural': 'Song Rehearsal Notes'},
        ),
        migrations.RemoveField(
            model_name='songrehearsalnote',
            name='section_title',
        ),
        migrations.AlterField(
            model_name='songrehearsalnote',
            name='rehearsal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_notes', to='board.rehearsaldetails'),
        ),
        migrations.DeleteModel(
            name='RehearsalSection',
        ),
    ]
