# Generated by Django 5.2.2 on 2025-10-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_remove_songrehearsalnote_section_and_more'),
        ('songbook', '0007_song_revised_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongWithRehearsalNotes',
            fields=[
            ],
            options={
                'verbose_name': 'Song with Rehearsal Notes',
                'verbose_name_plural': 'Songs with Rehearsal Notes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('songbook.song',),
        ),
    ]
