# Generated by Django 5.2.2 on 2025-10-23 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0008_song_revised_on'),
        ('board', '0027_songwithrehearsalnotes'),
        
    ]

    operations = [
        migrations.AlterField(
            model_name='songrehearsalnote',
            name='song',
            field=models.ForeignKey(
                to='songbook.Song',
                on_delete=django.db.models.deletion.CASCADE,
            ),
        ),
    ]
