# Generated by Django 5.2.2 on 2025-10-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_auto_20251023_1126'),
        ('songbook', '0008_song_revised_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrehearsalnote',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_notes', to='songbook.song'),
        ),
    ]
