# Generated by Django 5.2.2 on 2026-09-23 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0029_alter_rehearsaldetails_notes_delete_performance'),
        ('core', '0002_seed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcolumn',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_columns', to='core.group'),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.group'),
        ),
        migrations.AddField(
            model_name='venue',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='core.group'),
        ),
    ]
