# Generated by Django 5.2.2 on 2025-11-08 12:39

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0029_alter_songrehearsalnote_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehearsaldetails',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, help_text='General notes for this rehearsal', null=True),
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
