# Generated by Django 5.2.8 on 2025-12-14 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('notation', models.CharField(max_length=200)),
                ('repetitions', models.IntegerField(default=6, verbose_name='Répétitions')),
                ('difficulty', models.CharField(choices=[('apprenti', 'Apprenti Cubi'), ('confirme', 'Cubiste Confirmé'), ('speedcube', 'Speedcubiste'), ('maitre', 'Maître Cubi')], max_length=20, verbose_name='Niveau')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Algorithme',
                'verbose_name_plural': 'Algorithmes',
                'ordering': ['difficulty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_ms', models.IntegerField(verbose_name='Temps (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.algorithm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'entraînement",
                'verbose_name_plural': "Sessions d'entraînement",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'algorithm', '-created_at'], name='training_tr_user_id_813803_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_time_ms', models.IntegerField(verbose_name='Meilleur temps (ms)')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Tentatives totales')),
                ('last_practiced', models.DateTimeField(auto_now=True, verbose_name='Dernière pratique')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.algorithm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progrès utilisateur',
                'verbose_name_plural': 'Progrès utilisateurs',
                'unique_together': {('user', 'algorithm')},
            },
        ),
    ]
